# Generated by Django 3.2.17 on 2023-03-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='chapter',
            new_name='title',
        ),
    ]
